# GitLab CI/CD Pipeline for Home CI/CD Server
# Runs E2E tests on every push and merge request

stages:
  - test
  - validate

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# E2E Test Job
e2e-tests:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash curl
  script:
    - cd tests/e2e
    - chmod +x run-e2e-tests.sh
    - ./run-e2e-tests.sh --keep-image
  artifacts:
    when: always
    paths:
      - tests/e2e/logs/
    expire_in: 30 days
  timeout: 60m
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# Script Validation Job
validate-scripts:
  stage: validate
  image: ubuntu:24.04
  before_script:
    - apt-get update
    - apt-get install -y bash shellcheck
  script:
    - echo "Validating bash scripts..."
    - find scripts/deployment -name "*.sh" -exec bash -n {} \;
    - echo "Running shellcheck..."
    - find scripts/deployment -name "*.sh" -exec shellcheck {} + || true
  allow_failure: true

# Only run on merge requests and main branches
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
    - if: $CI_PIPELINE_SOURCE == "web"
